swn/applications/blog/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    #url para pagina principal de blog
    url(r'^articulos-en-empresas-y-desarrollo-de-sistemas-web-cusco/blog$',
        views.BlogView.as_view(),
        name='blog-index'
    ),
    #url para filtrar por categoria principal
    url(r'^sistemas-web-cusco/(?P<slug>[-\w]+)/$',
        views.FilterBlogView.as_view(),
        name='blog-filter'
    ),
    #url para ver el detalede un blog
    url(r'^blog-leer/(?P<slug>[-\w]+)/$',
        views.BLogDetailview.as_view(),
        name='blog-detail'
    ),

    #url para home
    url(r'^blog/(?P<slug>\w+)/$',
        views.BlogCategoriaListView.as_view(),
        name='blog_category-list'
    ),

    url(r'^blog$',
        views.BlogListView.as_view(),
        name='blog-list'
    ),

    url(
        r'^blog/(?P<category>[-\w]+)/(?P<slug>[-\w]+)/$',
        views.BlogCreatedComentaryView.as_view(),
        name='blog-detail_come'
    ),

]

swn/applications/cotizacion/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    #para index de cotizacion
    url(r'^cotiza-tu-proyecto-de-software-cusco/$',
        views.CotizacionView.as_view(),
        name='cotizacion-index'
    ),



    ####urls para servicos
    url(r'^', include('applications.cotizacion.url_services', namespace="cotizacion_url_services")),
]

swn/applications/productos/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    #url para index de productos o vitrina
    url(r'^nuestros-productos-de-software-cusco/$',
        views.ProductosView.as_view(),
        name='productos-index'
    ),
    #url para ver el detalede un producto
    url(r'^software-cusco/(?P<slug>[-\w]+)/$',
        views.ProductDetailview.as_view(),
        name='productos-detail'
    ),
    #url para index de cita
    url(r'^registrar-cita/$',
        views.CitationCreateView.as_view(),
        name='productos_cita-index'
    ),
    #url para registrar cita de producto
    url(r'^reservar-cita/(?P<slug>[-\w]+)/(?P<pk>\d+)/$',
        views.CitationProductCreateView.as_view(),
        name='productos_cita-add'
    ),
]

swn/swn/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
#from django.views.generic.base import RedirectView
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #urls para aplicacion blog
    url(r'^', include('applications.home.urls', namespace='home_app')),
    #url para aplicicon cotizacion
    url(r'^', include('applications.cotizacion.urls', namespace='cotizacion_app')),
    #url para aplicacion productos
    url(r'^', include('applications.productos.urls', namespace='productos_app')),
    #url para aplicacion blog
    url(r'^', include('applications.blog.urls', namespace="blog_app")),

    #url para editor de texto
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

swn/templates/include/footer.html
<div class="footer">
  <h5 class="footer__title">Puede contactar con neunapp por medio de nuestra redes sociales</h5>
  <div class="grid-x grid-margin-x align-center">
    <div class="cell shrink">
      <a target="_blank" href="https://www.facebook.com/Neunapp-954270137941159/?ref=aymt_homepage_panel" class="footer__btn__principal">
        <i class="fa fa-facebook-square fa-2x footer__icon" aria-hidden="true"></i>
        Facebook
      </a>
    </div>
    <div class="cell shrink">
      <a target="_blank" href="https://www.youtube.com/channel/UCcZoaMlaUXf_0KFXrEWt2Ww/videos?view_as=subscriber" class="footer__btn__secundario">
        <i class="fa fa-youtube-square fa-2x footer__icon" aria-hidden="true"></i>
        Youtube
      </a>
    </div>
  </div>
</div>

swn/templates/include/header.html
<div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
  <div class="title-bar-title">Menu</div>
</div>

<div class="top-bar header" id="responsive-menu">
  <div class="top-bar-left header-left">
    <ul class="menu">
      <h1 class="header__logo">
        <a href="/" class="header__logo__link">Neunapp</a>
      </h1>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu__item">
        <a href="/" class="menu__item__link">Inicio</a>
      </li>
      <li class="menu__item">
        <a href="{% url 'cotizacion_app:cotizacion-index' %}" class="menu__item__link">Cotización</a>
      </li>
      <li class="menu__item">
        <!-- <a href="{% url 'productos_app:productos-index' %}" class="menu__item__link">Vitrina</a> -->
        <a href="#" class="menu__item__link">Vitrina</a>
      </li>
      <li class="menu__item">
        <a href="{% url 'blog_app:blog-index' %}" class="menu__item__link">Blog</a>
      </li>
      <li class="menu__item">
        <a href="{% url 'productos_app:productos_cita-index' %}" class="menu__item__link">Cita</a>
      </li>
    </ul>
  </div>
</div>
<div class="header_space">

</div>