swn/applications/blog/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    #url para pagina principal de blog
    url(r'^articulos-en-empresas-y-desarrollo-de-sistemas-web-cusco/blog$',
        views.BlogView.as_view(),
        name='blog-index'
    ),
    #url para filtrar por categoria principal
    url(r'^sistemas-web-cusco/(?P<slug>[-\w]+)/$',
        views.FilterBlogView.as_view(),
        name='blog-filter'
    ),
    #url para ver el detalede un blog
    url(r'^blog-leer/(?P<slug>[-\w]+)/$',
        views.BLogDetailview.as_view(),
        name='blog-detail'
    ),

    #url para home
    url(r'^blog/(?P<slug>\w+)/$',
        views.BlogCategoriaListView.as_view(),
        name='blog_category-list'
    ),

    url(r'^blog$',
        views.BlogListView.as_view(),
        name='blog-list'
    ),

    url(
        r'^blog/(?P<category>[-\w]+)/(?P<slug>[-\w]+)/$',
        views.BlogCreatedComentaryView.as_view(),
        name='blog-detail_come'
    ),

]

swn/swn/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
#from django.views.generic.base import RedirectView
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #urls para aplicacion blog
    url(r'^', include('applications.home.urls', namespace='home_app')),
    #url para aplicicon cotizacion
    url(r'^', include('applications.cotizacion.urls', namespace='cotizacion_app')),
    #url para aplicacion productos
    url(r'^', include('applications.productos.urls', namespace='productos_app')),
    #url para aplicacion blog
    url(r'^', include('applications.blog.urls', namespace="blog_app")),

    #url para editor de texto
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

swn/applications/blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

# standard library
from datetime import timedelta, datetime

# third-party
from model_utils.models import TimeStampedModel
from ckeditor_uploader.fields import RichTextUploadingField

#django
from django.db import models
from django.conf import settings
from django.utils.encoding import python_2_unicode_compatible
from django.template.defaultfilters import slugify

#managers
from .managers import BlogManager, CategoryManager



@python_2_unicode_compatible
class Tag(TimeStampedModel):
    """django data model tag"""

    name = models.CharField('tag', max_length=20)

    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'
        ordering = ['-created']

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class MasterCategory(TimeStampedModel):
    """django data model categoria principal"""

    show_name = models.CharField('nombre', max_length=30, blank=True)
    name = models.CharField('nombre', max_length=100)
    slug = models.SlugField(editable=False, max_length=200)

    class Meta:
        verbose_name = 'Categoria principal'
        verbose_name_plural = 'Categorias principales'
        ordering = ['-created']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        str = self.name
        slug_unique = str.replace(" ", "-")
        self.slug = slugify(slug_unique)
        super(MasterCategory, self).save(*args, **kwargs)


@python_2_unicode_compatible
class Category(TimeStampedModel):
    """django data model categoria"""

    name = models.CharField('nombre', max_length=30)
    master_category = models.ForeignKey(
        MasterCategory,
        verbose_name='categoria_master',
        blank=True,
        null=True,
    )
    slug = models.SlugField(editable=False, max_length=200)
    objects = CategoryManager()

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'
        ordering = ['-created']

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        str = self.name
        slug_unique = str.replace(" ", "-")
        self.slug = slugify(slug_unique)
        super(Category, self).save(*args, **kwargs)


@python_2_unicode_compatible
class Blog(TimeStampedModel):
    """Django data model Blog"""

    title = models.CharField('titulo', max_length=200)
    description = models.TextField('descripcion')
    content = RichTextUploadingField('contenido')
    category = models.ForeignKey(Category, verbose_name='categoria')
    image = models.ImageField(upload_to='blog', verbose_name='imagen')
    slug = models.SlugField(editable=False, max_length=250)
    views = models.PositiveIntegerField('vistas', default=0, editable=False)
    tag = models.ManyToManyField(Tag, verbose_name='tag')
    published = models.BooleanField('publicado', default='false')
    score = models.PositiveIntegerField('puntuacion', default=0, editable=False)
    author = models.CharField('autor', max_length=200)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='created_Blog'
    )
    modified_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        related_name='modified_Blog'
    )
    objects = BlogManager()

    class Meta:
        verbose_name = 'Blog'
        verbose_name_plural = 'Blogs'
        ordering = ['-created']

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.id:
            # calculamos el total de segundos de la hora actual
            now = datetime.now()
            total_time = timedelta(
                hours=now.hour,
                minutes=now.minute,
                seconds=now.second
            )
            seconds = int(total_time.total_seconds())
            slug_unique = '%s %s' % (self.title, str(seconds))
        else:
            seconds = self.slug.split('-')[-1]  # recuperamos los segundos
            slug_unique = '%s %s' % (self.title, str(seconds))

        self.slug = slugify(slug_unique)
        super(Blog, self).save(*args, **kwargs)



@python_2_unicode_compatible
class Subscription(TimeStampedModel):
    """django data model suscripcion"""

    email = models.EmailField('email')

    class Meta:
        verbose_name = 'subcripcion'
        verbose_name_plural = 'subcripciones'
        ordering = ['-created']

    def __str__(self):
        return self.email


@python_2_unicode_compatible
class Commentary(TimeStampedModel):
    """django data model comentario"""

    blog = models.ForeignKey(
        Blog,
        verbose_name='blog'
    )
    description = models.CharField(
        'descripcion',
        max_length=300
    )
    email = models.EmailField('email')
    nick = models.CharField('apodo', max_length=30)


    class Meta:
        verbose_name = 'Comentario'
        verbose_name_plural = 'comentarios'
        ordering = ['-created']

    def __str__(self):
        return self.nick

swn/applications/blog/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django import forms

from .models import Commentary

class SearchForm(forms.Form):
   '''
   formulario para buscar notas
   '''

   kword = forms.CharField(
       max_length='300',
       required=False,
       widget=forms.TextInput(
           attrs={
                'class':'blog-form__input',
                'placeholder': 'Buscar'
           }
       )
   )



class ComentarybyBlogForm(forms.ModelForm):
    """
    formulario para agregar comentarios a los temas del blog
    """

    class Meta:
        model = Commentary
        fields = (
            'email',
            'nick',
            'description',
        )
        widgets = {
            'email': forms.TextInput(
                attrs={
                    'placeholder': 'email',
                }
            ),
            'nick': forms.TextInput(
                attrs={
                    'placeholder': 'nickname',
                }
            ),
            'description': forms.Textarea(
                attrs={
                    'placeholder': 'descripcion',
                }
            ),
        }

swn/applications/blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy, reverse

from django.views.generic import (
    CreateView,
    UpdateView,
    TemplateView,
    DeleteView,
    DetailView,
    FormView,
    ListView
)

from django.views.generic.edit import FormMixin
# Create your views here.

#application home
from applications.home.forms import BlogSuscriptionForm

#app blog
from .models import Blog, Category, Commentary, MasterCategory
#local forms
from .forms import SearchForm,ComentarybyBlogForm


#vistas para blog
class BlogView(ListView):
    """ pantalla principal de blog"""

    context_object_name = 'blogs'
    template_name = 'blog/index.html'

    def get_context_data(self, **kwargs):
        context = super(BlogView, self).get_context_data(**kwargs)
        context['form'] = SearchForm
        context['master_categorys'] = MasterCategory.objects.order_by('created')
        return context

    def get_queryset(self):
        #recuperamos el valor por GET
        q = self.request.GET.get("kword", '')
        queryset = Blog.objects.search_blog(q)
        return queryset


#vistas para blog
class FilterBlogView(ListView):
    """ pantalla principal con filtro de blog"""

    context_object_name = 'blogs'
    template_name = 'blog/index.html'

    def get_context_data(self, **kwargs):
        context = super(FilterBlogView, self).get_context_data(**kwargs)
        context['form'] = SearchForm
        context['master_categorys'] = MasterCategory.objects.order_by('created')
        return context

    def get_queryset(self):
        #recuperamos valor de url
        master_category = self.kwargs['slug']
        #recuperamos el valor por GET
        q = self.request.GET.get("kword", '')
        queryset = Blog.objects.filter_blog_by_master_category(master_category,q)
        return queryset


class BLogDetailview(FormMixin, DetailView):
    """
    vista que muestra detalle blog
    """

    model = Blog
    #formlario para suscripcion
    form_class = BlogSuscriptionForm
    template_name = 'blog/detail.html'

    def get_success_url(self):
        return '.'

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.save()
        return super(BLogDetailview, self).form_valid(form)


###
class BlogListView(ListView):

   context_object_name = 'blogs'
   template_name = 'blog/list.html'

   def get_context_data(self, **kwargs):
       context = super(BlogListView, self).get_context_data(**kwargs)
       context['form'] = SearchForm
       context['categorias'] = Category.objects.list_category()
       return context

   def get_queryset(self):
       #recuperamos el valor por GET
       q = self.request.GET.get("kword", '')
       queryset = Blog.objects.search_blog(q)
       #queryset_category = Category.objects.list_category()
       return queryset
      # return {'blogs':queryset,'categories':queryset_category}


class BlogCategoriaListView(ListView):
   """
   vista que lista caterias por blog
   """

   context_object_name = 'categories'
   template_name = 'blog/by_category.html'

   def get_context_data(self, **kwargs):
       context = super(BlogCategoriaListView, self).get_context_data(**kwargs)
       category = self.kwargs['slug']
       context['form'] = SearchForm
       context['blogs'] = Blog.objects.search_blog_by_category(category)
       return context

   def get_queryset(self):
       #recuperamos el valor por GET
       blog = self.request.GET.get("kword", '')
       category = self.kwargs['slug']
       queryset = Blog.objects.search_blogxcategory(category)
       #queryset_category = Category.objects.list_category()
       return queryset
      # return {'blogs':queryset,'categories':queryset_category}


class BlogCreatedComentaryView(FormMixin, DetailView):
    """
    vista que su agrega un comentario blog
    """

    model = Blog
    template_name = 'blog/detail.html'
    form_class = ComentarybyBlogForm

    def get_success_url(self):
        return reverse_lazy('/')


    def get_context_data(self, **kwargs):
        context = super(BlogCreatedComentaryView, self).get_context_data(**kwargs)
        context['form']= self.get_form()
        #obtenemos'

        blog = self.object
        context['commentary'] = Commentary.objects.filter(blog=blog).order_by('-created')
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


    def form_valid(self, form):

        email = form.cleaned_data['email']

        nick = form.cleaned_data['nick']

        description = form.cleaned_data['description']

        blog = self.object

        comentario = Commentary(
            email = email,
            nick = nick,
            description = description,
            blog = blog
        )
        comentario.save()
        return super(BlogCreatedComentaryView, self).form_valid(form)

swn/templates/blog/base_blog.html
{% extends "base.html" %}

{% load  staticfiles %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">

  <meta name="google-site-verification" content="ei3LI-u5d-yvQhEAj85RpRyYJAnDlfV-6ItMtPruDbE" />

  <!-- Global Site Tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-92060033-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments)};
    gtag('js', new Date());

    gtag('config', 'UA-92060033-1');
  </script>

{% endblock css %}

{% block js %}
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/foundation.min.js' %}"></script>
  <script src="{% static 'js/app.js' %}"></script>
{% endblock js %}

swn/templates/blog/by_category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form  method="get">{% csrf_token %}
      {{form.kword}}
    <button type="submit">Buscar</button>
</form>
<h1>lista de resultados</h1>

{% for b in blogs  %}
    <p>
        {{ b.image }}
    </p>
    <p>
        {{ b.title }}
    </p>
    <p>
        {{ b.description }}
    </p>
    -----------------------------------------------
{% endfor %}
</body>
</html>

swn/templates/blog/detail.html
{% extends "blog/base_blog.html" %}

{% load  staticfiles %}

{% load thumbnail %}

{% load l10n %}

{% block title %}
  Sistemas web Cusco | {{object.title}}
{% endblock %}

{% block description %}
  {{ object.description }}
{% endblock %}

{% block tags %} {% for tag in blog.tag.all %}{{tag}}, {% endfor %} {% endblock tags %}

{% block content %}
  {% include "include/header.html" %}

  <!-- Inicio detalle blog -->
  <div class="grid-container blog-detail">
    <div class="grid-x align-center blog-detail__header">
      <div class="cell small-12 medium-6 blog-detail__header__fondo">
        <img src="{{object.image.url}}" alt="" class="blog-detail__header__fondo__img">
      </div>
      <div class="cell small-12 medium-6 blog-detail__header__content">
        <p class="blog-detail__header__content__title">{{object.title}}</p>
        <p class="blog-detail__header__content__author">Autor: {{object.author}}</p>
        <p class="blog-detail__header__content__text">
          {{object.description}}
        </p>
      </div>
    </div>

    <div class="grid-x align-center">
      <div class="cell blog-detail-resume">
        {{object.content|safe}}
      </div>
    </div>

    <!-- suscription -->
    <div class="blog-suscription">
      <p class="cell blog-detail__suscription__title">Déjanos tu correo y entérate de mas de estos artículos:</p>
      <form class="blog-detail__suscription"method="post">{% csrf_token %}
        {{form.email}}
        <input type="submit" class="blog-detail__suscription__btn" name="suscripcion" value="Suscribirme">
      </form>
    </div>

    <!-- fin suscripton -->

    <div class="grid-x grid-margin-x align-center">
      {% for tag in blog.tag.all %}
        <div class="cell shrink blog-detail-tags">
          <a href="#" class="blog-detail-tag">{{tag.name}}</a>
        </div>
      {% endfor %}
    </div>
  </div>
  <!-- Fin detalle blog -->

  {% include "include/footer.html" %}
{% endblock %}

swn/templates/blog/detail_1.html
<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Blog {{ object.name }}</title>
</head>
<body>

<h1>{{ object.title }}</h1>
<p>{{ object.image }}</p>
-------------------------------
<p>{{ object.description }}</p>
----------------------------
<p>{{ object.content }}</p>
---------------------
<p>{{ object.score }}</p>
---------------------
<p>{{ object.author }}</p>

<form action="#" method="POST">
    {% csrf_token %}
    {{form}}
    <input type="submit" value="Send request">
</form>

{% for c in commentary  %}
    <p>Fecha de creacion: {{ c.created }}</p>
   <p>Apodo: {{ c.nick }}</p>
   <p>Comentario: {{ c.description }} </p>
    -----------------------------------------------
{% endfor %}

</body>
</html>

swn/templates/blog/index.html
{% extends "blog/base_blog.html" %}

{% load  staticfiles %}

{% load thumbnail %}

{% load l10n %}

{% block title %}
  Sistemas web Cusco | empresas y tecnologia
{% endblock %}

{% block description %}
  Construimos Sistemas web, y diseño de paginas web, estamos en cusco. quieres una aplicacion movil, una pagina web,
  un sistema para tu empresa.
{% endblock %}

{% block content %}
  {% include "include/header.html" %}

  <!-- Inicio de Blog -->
  <div class="grid-container">
    <div class="grid-x grid-margin-x blog">
      <h1 class="cell blog__title">Nuestros artículos en: Tecnología - Empresas - Emprendimiento - Software</h1>
      <div class="cell samll-12">
        <form class="blog-form" method="get"> {% csrf_token %}
          {{form.kword}}
          <input type="submit" class="blog-form__btn" name="buscar" value="Buscar">
        </form>
      </div>
      <div class="cell small-12 blog-header">
        {% for mc in master_categorys %}
          <a class="blog-header__item"href="{% url 'blog_app:blog-filter' mc.slug %}">{{mc.show_name}}</a>
        {% endfor %}
      </div>
      {% for blog in blogs  %}
        <div class="cell small-12 medium-6 large-4 blog-item">
          <img src="{{blog.image.url}}" alt="{{blog.title}}" class="blog-item__img">
          <p><a href="{% url 'blog_app:blog-detail' blog.slug %}" class="blog-item__title">{{blog.title}}</a></p>
        </div>
      {% endfor %}
    </div>
  </div>
  <!-- Fin de Blog -->

  {% include "include/footer.html" %}

{% endblock %}

swn/templates/blog/list.html
<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<form  method="get">{% csrf_token %}
      {{form.kword}}
    <button type="submit">Buscar</button>
</form>

<h1>lista de resultados</h1>
{% for c in categorias  %}
    <a href="#">
        {{ c.name }}
    </a>
    -----------------------------------------------
{% endfor %}
{% for b in blogs  %}
    <p>
        {{ b.image }}
    </p>
    <a href="{% url 'blog_app:blog-detail' b.category.slug b.slug %}">
        {{ b.title }}
    </a>
    -----------------------------------------------
{% endfor %}


</body>
</html>

swn/templates/blog/prueba.html
<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Prueba</title>
</head>
<body>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
</form>

</body>
</html>