swn/applications/blog/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    #url para pagina principal de blog
    url(r'^articulos-en-empresas-y-desarrollo-de-sistemas-web-cusco/blog$',
        views.BlogView.as_view(),
        name='blog-index'
    ),
    #url para filtrar por categoria principal
    url(r'^sistemas-web-cusco/(?P<slug>[-\w]+)/$',
        views.FilterBlogView.as_view(),
        name='blog-filter'
    ),
    #url para ver el detalede un blog
    url(r'^blog-leer/(?P<slug>[-\w]+)/$',
        views.BLogDetailview.as_view(),
        name='blog-detail'
    ),

    #url para home
    url(r'^blog/(?P<slug>\w+)/$',
        views.BlogCategoriaListView.as_view(),
        name='blog_category-list'
    ),

    url(r'^blog$',
        views.BlogListView.as_view(),
        name='blog-list'
    ),

    url(
        r'^blog/(?P<category>[-\w]+)/(?P<slug>[-\w]+)/$',
        views.BlogCreatedComentaryView.as_view(),
        name='blog-detail_come'
    ),

]

swn/applications/cotizacion/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    #para index de cotizacion
    url(r'^cotiza-tu-proyecto-de-software-cusco/$',
        views.CotizacionView.as_view(),
        name='cotizacion-index'
    ),



    ####urls para servicos
    url(r'^', include('applications.cotizacion.url_services', namespace="cotizacion_url_services")),
]

swn/applications/home/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from . import views

urlpatterns = [
    #url para pantalla principal
    url(r'^$',
        views.HomeView.as_view(),
        name='index'
    ),
    #url para mensaje
    url(r'^solicitud-confirmada/$',
        views.MensajeView.as_view(),
        name='mensaje'
    ),
]

swn/applications/productos/urls.py
from django.conf.urls import include, url
from . import views

urlpatterns = [
    #url para index de productos o vitrina
    url(r'^nuestros-productos-de-software-cusco/$',
        views.ProductosView.as_view(),
        name='productos-index'
    ),
    #url para ver el detalede un producto
    url(r'^software-cusco/(?P<slug>[-\w]+)/$',
        views.ProductDetailview.as_view(),
        name='productos-detail'
    ),
    #url para index de cita
    url(r'^registrar-cita/$',
        views.CitationCreateView.as_view(),
        name='productos_cita-index'
    ),
    #url para registrar cita de producto
    url(r'^reservar-cita/(?P<slug>[-\w]+)/(?P<pk>\d+)/$',
        views.CitationProductCreateView.as_view(),
        name='productos_cita-add'
    ),
]

swn/swn/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
#from django.views.generic.base import RedirectView
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #urls para aplicacion blog
    url(r'^', include('applications.home.urls', namespace='home_app')),
    #url para aplicicon cotizacion
    url(r'^', include('applications.cotizacion.urls', namespace='cotizacion_app')),
    #url para aplicacion productos
    url(r'^', include('applications.productos.urls', namespace='productos_app')),
    #url para aplicacion blog
    url(r'^', include('applications.blog.urls', namespace="blog_app")),

    #url para editor de texto
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

swn/applications/home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals


# third-party
from model_utils.models import TimeStampedModel
from django.db import models

# Create your models here.
class Suscription(TimeStampedModel):

    email = models.EmailField('email')

    class Meta:
        verbose_name = 'suscripcion'
        verbose_name_plural = 'suscripciones'
        ordering = ['-created']

    def __str__(self):
        return self.email

swn/applications/home/forms.py
# -*- coding: utf-8 -*-
from django import forms

from .models import Suscription


class SuscriptionForm(forms.ModelForm):
    """
    formulario para agregar citaciones
    """

    class Meta:
        model = Suscription
        fields = (
            'email',
        )
        widgets = {
            'email': forms.TextInput(
                attrs={
                    'class':'suscription__form__input',
                    'placeholder': 'Correo Electrónico',
                }
            ),
        }


class BlogSuscriptionForm(forms.ModelForm):
    """
    formulario para agregar citaciones
    """

    class Meta:
        model = Suscription
        fields = (
            'email',
        )
        widgets = {
            'email': forms.TextInput(
                attrs={
                    'class':'blog-detail__suscription__input',
                    'placeholder': 'Correo Electrónico',
                }
            ),
        }

swn/applications/home/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
#django library
from django.core.urlresolvers import reverse_lazy, reverse
from django.views.generic import (
    CreateView,
    UpdateView,
    DetailView,
    DeleteView,
    ListView,
    TemplateView,
    View,
)

#import app blog
from applications.blog.models import Blog
#import app productos
from applications.productos.models import Product

#import forms.py
from .forms import SuscriptionForm


class MensajeView(TemplateView):
    template_name = 'home/mensaje.html'


class HomeView(CreateView):
    '''registrar nuevo registro de suscripcion'''

    form_class = SuscriptionForm
    success_url = reverse_lazy('home_app:index')
    template_name = 'home/index.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['blogs'] = Blog.objects.search_blog('')[:3]
        #recupeamos productos principales
        prods = Product.objects.principal_product()
        #enviamos prods al home
        context['producto_1'] = prods[3]
        context['producto_2'] = prods[2]
        context['producto_3'] = prods[1]
        context['producto_4'] = prods[0]
        return context

swn/templates/home/base_home.html
{% extends "base.html" %}

{% load  staticfiles %}

{% block css %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">

  <meta name="google-site-verification" content="ei3LI-u5d-yvQhEAj85RpRyYJAnDlfV-6ItMtPruDbE" />

  <!-- Global Site Tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-92060033-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments)};
    gtag('js', new Date());

    gtag('config', 'UA-92060033-1');
  </script>

{% endblock css %}

{% block js %}
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/foundation.min.js' %}"></script>
  <script src="{% static 'js/app.js' %}"></script>

  <!-- Global Site Tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-92060033-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments)};
    gtag('js', new Date());

    gtag('config', 'UA-92060033-1');
  </script>

{% endblock js %}

swn/templates/home/index.html
{% extends "home/base_home.html" %}

{% load  staticfiles %}

{% load thumbnail %}

{% load l10n %}

{% block title %}
  Sistemas web Cusco | Diseño de paginas web en cusco
{% endblock %}

{% block description %} Somos un sitio web que se dedica al desarrollo de sistemas web y paginas web en cusco. navega y encuentra sistemas web de ventas en cusco, sistemas de inventario en cusco y diseños bontios de paginas web en cusco.  {% endblock %}
{% block tags %} Paginas web cusco, sistemas cusco peru, paginas web economicas en cusco, desarrollo de paginas web en cusco, sistemas web en cusco peru {% endblock tags %}
{% block content %}
  {% include "include/header.html" %}

  <!-- Inicio de banner  -->
  <div class="banner">
    <div class="orbit banner-container" role="region" aria-label="Favorite Space Pictures" data-orbit>
      <div class="orbit-wrapper">
        <ul class="orbit-container">
          <li class="is-active orbit-slide">
            <figure class="orbit-figure">
              <img class="orbit-image banner-img" src="{% static 'img/3.jpg' %}" alt="Sistemas web cusco">
            </figure>
          </li>
        </ul>
      </div>
    </div>
    <div class="banner__copy">
        <h1 class="banner__copy__title">Desarrollo de sistemas web.</h1>
        <p class="banner__copy__text">Hagamos que el internet sea mucho más que una página web.</p>
        <div class="banner__copy__controls">
          <a href="{% url 'productos_app:productos_cita-index' %}" class="banner__copy__controls__btn principal">
            <i class="fa fa-handshake-o" aria-hidden="true"></i>
            Quiero Una Cita
          </a>
          <a href="{% url 'cotizacion_app:cotizacion-index' %}" class="banner__copy__controls__btn secundario">
            <i class="fa fa-cart-plus" aria-hidden="true"></i>
            Cotizaciones
          </a>
        </div>
      </div>
    </div>
  </div>
  <!--  fin de banner -->

  <!-- Servicios -->
  <div class="grid-x align-center services">
    <div class="cell small-12 medium-4 large-3 services__item">
      <i class="fa fa-desktop fa-5x services__icon" aria-hidden="true"></i>
      <p class="services__item__title">Software a medida</p>
      <p class="services__item__description">Construyamos juntos el software que mejor encaja con sus clientes y su trabajo.</p>
    </div>
    <div class="cell small-12 medium-4 large-3 services__item">
      <i class="fa fa-diamond fa-5x services__icon" aria-hidden="true"></i>
      <p class="services__item__title">Diseño agradable</p>
      <p class="services__item__description">Sus herramientas de trabajo son tambien parte de su empresa. Hagamos que se vea bien.</p>
    </div>
    <div class="cell small-12 medium-4 large-3 services__item">
      <i class="fa fa-check fa-5x services__icon" aria-hidden="true"></i>
      <p class="services__item__title">Carga Rápida</p>
      <p class="services__item__description">Que la estadía de sus clientes en su plataforma web sea agradable, y no molesta por cargas lentas.</p>
    </div>
  </div>
  <!-- fin de servicios -->

  <!-- Productos-->
  <div class="grid-x align-center prods">
    <div class="cell small-12 large-5 prods__content">
      <p class="prods__content__title">{{producto_1.name}}</p>
      <p class="prods__content__text">
        {{producto_1.description_show}}
      </p>
      <div class="prods__content__btns">
        <a class="prods__content__btns__item secundario" href="{% url 'productos_app:productos-detail' producto_1.slug %}">
          <i class="fa fa-play-circle-o fa-1x prods__icon" aria-hidden="true"></i>
          Ver Producto
        </a>
        <a class="prods__content__btns__item principal" href="{% url 'productos_app:productos_cita-add' producto_1.slug producto_1.pk %}">
          <i class="fa fa-pencil-square fa-1x prods__icon" aria-hidden="true"></i>
          Reservar Cita
        </a>
      </div>
    </div>
    <div class="cell small-12 large-5 prods__image">
      <img class="prods__image__img" src="{{producto_1.image.url}}" alt="{{producto_2.name}}">
    </div>
  </div>

  <div class="grid-x align-center prods grid-secondary">
    <div class="cell small-12 large-5 prods__content">
      <p class="prods__content__title">{{producto_2.name}}</p>
      <p class="prods__content__text">
        {{producto_2.description_show}}
      </p>
      <div class="prods__content__btns">
        <a class="prods__content__btns__item secundario" href="{% url 'productos_app:productos-detail' producto_2.slug %}">
          <i class="fa fa-play-circle-o fa-1x prods__icon" aria-hidden="true"></i>
          Ver Producto
        </a>
        <a class="prods__content__btns__item principal" href="{% url 'productos_app:productos_cita-add' producto_2.slug producto_2.pk %}">
          <i class="fa fa-pencil-square fa-1x prods__icon" aria-hidden="true"></i>
          Reservar Cita
        </a>
      </div>
    </div>
    <div class="cell small-12 large-5 prods__image">
      <img class="prods__image__img" src="{{producto_2.image.url}}" alt="{{producto_2.name}}">
    </div>
  </div>

  <div class="grid-x align-center prods">
    <div class="cell small-12 large-5 prods__content">
      <p class="prods__content__title">{{producto_3.name}}</p>
      <p class="prods__content__text">
        {{producto_3.description_show}}
      </p>
      <div class="prods__content__btns">
        <a class="prods__content__btns__item secundario" href="{% url 'productos_app:productos-detail' producto_3.slug %}">
          <i class="fa fa-play-circle-o fa-1x prods__icon" aria-hidden="true"></i>
          Ver Producto
        </a>
        <a class="prods__content__btns__item principal" href="{% url 'productos_app:productos_cita-add' producto_3.slug producto_3.pk %}">
          <i class="fa fa-pencil-square fa-1x prods__icon" aria-hidden="true"></i>
          Reservar Cita
        </a>
      </div>
    </div>
    <div class="cell small-12 large-5 prods__image">
      <img class="prods__image__img" src="{{producto_3.image.url}}" alt="{{producto_3.name}}">
    </div>
  </div>

  <div class="grid-x align-center prods grid-secondary">
    <div class="cell small-12 large-5 prods__content">
      <p class="prods__content__title">{{producto_4.name}}</p>
      <p class="prods__content__text">
        {{producto_4.description_show}}
      </p>
      <div class="prods__content__btns">
        <a class="prods__content__btns__item secundario" href="{% url 'productos_app:productos-detail' producto_4.slug %}">
          <i class="fa fa-play-circle-o fa-1x prods__icon" aria-hidden="true"></i>
          Ver Producto
        </a>
        <a class="prods__content__btns__item principal" href="{% url 'productos_app:productos_cita-add' producto_4.slug producto_4.pk %}">
          <i class="fa fa-pencil-square fa-1x prods__icon" aria-hidden="true"></i>
          Reservar Cita
        </a>
      </div>
    </div>
    <div class="cell small-12 large-5 prods__image">
      <img class="prods__image__img" src="{{producto_4.image.url}}" alt="{{producto_4.name}}">
    </div>
  </div>
  <!-- fin de productos-->

  <!-- suscripcion -->
  <div class="suscription">
    <p class="suscription__title">Suscríbete y recibe noticias sobre software y actualidad</p>
    <form class="suscription__form" method="post">{% csrf_token %}
      {{form.email}}
      <input type="submit" class="suscription__form__btn" value="Suscribirme">
    </form>
  </div>
  <!-- fin suscripcion -->

  <!-- blog recientes -->
  <div class="grid-x align-center recents">
    {% for blog in blogs  %}
      <div class="cell small-12 large-3 recents__item">
        <img class="recents__item__img" src="{{blog.image.url}}" alt="">
        <a href="{% url 'blog_app:blog-detail' blog.slug %}" class="recents__item__title">{{blog.title}}</a>
        <p class="recents__item__text">
          {{blog.description|truncatechars_html:150}}
        </p>
      </div>
    {% endfor %}
  </div>
  <!-- fin blog recientes -->
  {% include "include/footer.html" %}

{% endblock %}

swn/templates/home/mensaje.html
{% extends "home/base_home.html" %}

{% load  staticfiles %}

{% load thumbnail %}

{% load l10n %}

{% block title %}
  Sistemas web Cusco | desarrollo de sistemas web | diseño de paginas web en cusco
{% endblock %}

{% block description %}
  Construimos Sistemas web, y diseño de paginas web, estamos en cusco. quieres una aplicacion movil, una pagina web,
  un sistema para tu empresa.
{% endblock %}

{% block content %}
  {% include "include/header.html" %}

  <!-- tarjeta de confirmacion -->
  <div class="grid-container">
    <div class="grid-x grid-padding-x align-center mensaje">
      <div class="cell small-12 large-8 mensaje__content">
        <div class="callout mensaje__content__card">
          <h5 class="mensaje__content__card__title">
            Solicitud Registrada
            <i class="fa fa-smile-o" aria-hidden="true"></i>
          </h5>
          <p class="mensaje__content__card__text">Hemos registrado su solicitud, muy pronto estaremos en contacto con Ud.</p>
          <a href="/" class="mensaje__content__card__link">Seguir navegando por Neunapp.</a>
        </div>
      </div>
    </div>
  </div>
  <!-- fin tarjeta de confirmacion -->

  {% include "include/footer.html" %}

{% endblock %}